# -*- coding: utf-8 -*-
"""PLN_semana02_regex_Wagner_Alves_da_Silva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyszWIs8UZMbpXh23Bzn0gMyIEf0Q5hX

#Expressões Regulares em Python
## Tecnólogo em Inteligência Artificial Aplicada - Processamento de Linguagem Natural
Nesta atividade você entrará em contato com **Expressões Regulares (RegEx)**, talvez a mais importante ferramenta de PLN para descrever/encontrar/substituir padrões de texto. Após esta atividade você será capaz de ler uma expressão regular como essa `^[0-9]{1,3}(\.[0-9]{1,3}){1,3}$`, como você lê um texto em português.

##**ATIVIDADE PRÁTICA**
Atividades de fixação no uso de Expressões Regulares

### 1) Obtenha todas palavras do texto
"""

import re
texto = "Um texto qualquer sem qualquer valor semântico."

re.findall(r".+",texto)

"""### 2) Obtenha a primeira palavra do texto"""

texto2 = "Um texto qualquer sem qualquer valor semântico."

match = re.match(r".{2}",texto2)
match

"""### 3) Obtenha a posição de início do primeiro espaço (white-space) encontrado no texto a seguir"""

import re
texto3 = "Um texto qualquer sem qualquer valor semântico."

re.search(r"\s", texto3)

"""### 4) Obtenha os dois primeiros caracteres de cada palavra
Dica: Pesquise sobre o caracter de word boundary `\b`, que encontra as delimitações de cada palavra
"""

texto4 = "Um texto qualquer sem qualquer valor semântico."

import re
re.findall (r"\b[a-zA-Z]{2}", texto4)

"""### 5) Obtenha datas no formato brasileiro (dd/mm/aaaa) e americano (aaaa-mm-dd)"""

texto5 = "Data: 27/02/1987. Date: 1987-02-27."
re.findall(r"[0-9/]+[0-9\-]{1,}" , texto5)

"""### 6) Obtenha todas palavras que terminem com vogal"""

texto6 = "Um texto qualquer sem qualquer valor semântico."
re.findall(r"\w+[aieou]{1}\b",texto6)

"""### 7) Substitua toda ocorrência da palavra "Avenida" por "Av.""""

texto7 = "Endereço: Avenida Getúlio Vargas, 1811\n Endereço: avenida visconde de guarapuava, 1533"
re.sub(r"Avenida | avenida","Av.",texto7)

"""###8) Obtenha os endereços sem a numeração"""

texto8 = "Endereço: Avenida Getúlio Vargas, 1811\nEndereço: avenida visconde de guarapuava, 1533"
re.findall(r"[^\d]+",texto8)

"""### 9) Substitua todas ocorrências de espaços, vírgulas e pontos pelo underline"""

text9 = 'Python Exercises, PHP exercises.'
re.sub(r" |\, | \.","_", text9)

"""## Referências e Material complementar


*   [RegEx Cheat Sheet](https://www.rexegg.com/regex-quickstart.html)
*   [Tutorial sobre expressões regulares para iniciantes em Python](https://www.vooo.pro/insights/tutorial-sobre-expressoes-regulares-para-iniciantes-em-python/)
*   [Python Regular Expressions by Google](https://developers.google.com/edu/python/regular-expressions)
*   [Python ReGex Exercises](https://www.w3resource.com/python-exercises/re/)

Este notebook foi produzido por Prof. [Lucas Oliveira](http://lattes.cnpq.br/3611246009892500).
"""